### ISSUE TITLE
Localization options

### ISSUE THREAD

**Issue by Cipherwraith** [Cipherwraith/5ch#2]
We need localization options for every string that gets added to this javascript. Its best to think about this from the earliest stages so that we dont need to back track and put everything into a database later.

Anybody have thoughts about the best way to add localization?

**Comment by ctrlcctrlv** [comment]
It's already done.

https://github.com/Cipherwraith/2ch/blob/master/gruntfile.js#L15

`--ja` flag builds Japanese version by adding script https://github.com/Cipherwraith/2ch/blob/master/locale/ja_JP.json to beginning.

Strings passed through function `_()` are automatically translated.

All we need is translations and strings to translate :wink:

**Comment by Cipherwraith** [comment]
<img width="475" alt="screen shot 2015-10-16 at 4 12 50 pm" src="https://cloud.githubusercontent.com/assets/5457807/10535750/65bd336a-7420-11e5-9ac6-08d94955f492.png">

Now I see that localization of strings is already available in the code; the problem is that the locales werent used. Please consider putting all future strings into the locale files.

**Comment by ctrlcctrlv** [comment]
All it takes is running a script; I'd rather not bother a translator with it until we have all the strings that need translation.
